CREATE TABLE respostas (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
nome TEXT NOT NULL,
curso TEXT NOT NULL,
pontuacao INTEGER NOT NULL,
total_criterios INTEGER NOT NULL,
created_at TIMESTAMP DEFAULT NOW()
);